### ISSUE TITLE
Add facebook collection and item to staging API

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/cloud-optimized-data-pipelines#104]
Data set exists in testing API: https://j2wlly6xg8.execute-api.us-east-1.amazonaws.com/collections/facebook_population_density

@slesaad was working on automating the COG generation in this ticket #78 

This ticket is just to publish the existing COG collection and item STAC metadata to the staging API, following https://github.com/NASA-IMPACT/delta-backend/issues/29 and https://github.com/NASA-IMPACT/delta-backend/issues/28

**Comment by slesaad** [comment]
Added the stac medata for the collection and item to the staging api. You can find it in the following links:
Collection: https://staging-stac.delta-backend.xyz/collections/facebook_population_density
Item: https://staging-stac.delta-backend.xyz/collections/facebook_population_density/items

cc: @abarciauskas-bgse @anayeaye

**Comment by abarciauskas-bgse** [comment]
LGTM @anayeaye do you want to take a look?

**Comment by anayeaye** [comment]
I forgot to comment, but did look at these a while back and they look good to me, too
