### ISSUE TITLE
Design: VEDA datasets should be in an MCP bucket

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/cloud-optimized-data-pipelines#118]
## Motivation

We need all the data to be in an MCP-controlled AWS account, presumably the same account that will eventually run the production STAC API and interfaces (dashboard). My understanding is a NASA security requirement in order to release our interfaces to an audience outside of NASA internal development groups.

## Description
We have many users of the VEDA data store and API:

* EIS inputs
* EIS outputs
* NASA Dashboard datasets 
* Trilateral Dashboard datasets
* GIBS / Worldview datasets
* ADC datasets

I believe these should all be in on MCP VEDA Account bucket, which I would just propose to call `s3://veda-data-store`

## Acceptance Criteria:
- Data is stored in a bucket in an MCP AWS account
- Data is discoverable and accessible to users that need it
- Don't maintain multiple copies of data if we can avoid it. There will be multiple environments for our applications but data should only be stored in one location to avoid paying multiple times for data storage.

## Questions:
* Which of the use cases may require data stored outside of our bucket and what are the things we need to enforce about those buckets or their parent AWS accounts?
* Datasets which the current STAC API relies on currently should be moved to that new bucket in MCP and we will need to update the metadata. We can probably do this with a script to update the database directly. Do we have concerns about doing that? cc @anayeaye 
* How do we want to organize the data store directory structure and enforce organization? All the data should be discovered via STAC API so their locations should be discoverable by users but in case we need to enforce any collection-specific monitoring or rules, should we at least have a requirement that there exists a subdirectory which matches the id of the STAC collection.
* Can we allow cloud-optimized-data-pipelines and other AWS identities (i.e. my IAM user) associated with the UAH Dev/Staging account for the `covid-dashboard` AWS account to PUT data to the MCP bucket? Presumably anyone with access to the Publish STAC Metadata API should also have access to this bucket.

## Checklist:

- [ ] Define standards for what data should be put where
- [ ] Develop a process for migrating the data (e.g. updating the pgSTAC databases)
- [ ] Define, configure and test access from covid-dashboard AWS account to PUT data to the MCP account

**Comment by abarciauskas-bgse** [comment]
@NASA-IMPACT/veda interested in any additional considerations I should include here.

**Comment by tracetechnical** [comment]
Do we need to sheep dip this data on the way in too?

**Comment by xhagrg** [comment]
> Which of the use cases may require data stored outside of our bucket and what are the things we need to enforce about those buckets or their parent AWS accounts?

How are we handling HLS or similar datasets? We do not want to copy over the data right? 

> How do we want to organize the data store directory structure and enforce organization? All the data should be discovered via STAC API so their locations should be discoverable by users but in case we need to enforce any collection-specific monitoring or rules, should we at least have a requirement that there exists a subdirectory which matches the id of the STAC collection.
Maintaining the same name across the collection and s3 bucket would be a good idea. 

> Can we allow cloud-optimized-data-pipelines and other AWS identities (i.e. my IAM user) associated with the UAH Dev/Staging account for the covid-dashboard AWS account to PUT data to the MCP bucket? Presumably anyone with access to the Publish STAC Metadata API should also have access to this bucket.

This probably points to the larger discussion we were having about how deployments/CICD is going to work in the MCP env. In the mean time, there are roles in the UAH env that can be assumed to access resources on the MCP side. We could certainly establish some roles to access the buckets in MCP. @michaelsfoley and @freitagb have more idea regarding this.

**Comment by abarciauskas-bgse** [comment]
Thanks @xhagrg for the feedback, in response to 

>How are we handling HLS or similar datasets? We do not want to copy over the data right?

I don't think we will make copies of any data that are already in Earthdata Cloud (unless we are producing some cloud-optimized version of that data, which is no longer a copy...)

I also opened this related ticket: https://github.com/NASA-IMPACT/veda-architecture/issues/21 to decide on where users should be allowed to publish data from.

**Comment by anayeaye** [comment]
> Datasets which the current STAC API relies on currently should be moved to that new bucket in MCP and we will need to update the metadata. We can probably do this with a script to update the database directly. Do we have concerns about doing that? 

No concerns , I don't see any reason why updating the asset href properties directly in the database would be a problem in pgstac < version 0.5. [Version 0.5](https://github.com/stac-utils/pgstac/pull/96) could be fine as well, but we'd need to review how items are 'dehydrated' first (process to strip item records of metadata that is common for the full collection and only store that common info in the collection record).

**Comment by xhagrg** [comment]
@abarciauskas-bgse can we close this issue out?

**Comment by abarciauskas-bgse** [comment]
Yes
