### ISSUE TITLE
Create new black marble collection and items for black marble nightlights data having with 3 bands (Hurricane event data)

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/cloud-optimized-data-pipelines#121]
@anayeaye noted that we need to add all 3 bands to have these nightlights visualized, see comment https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines/pull/111#issuecomment-1103971604

- [x] New collection in dev for Hurricanes Ida and Maria
- [x] New items in dev for Hurricanes Ida and Maria
- [x] Remove those from nightlights-hd-monthly existing collection in dev 
- [x] Verify metadata changes with team
- [x] Update staging

**Comment by xhagrg** [comment]
https://staging-stac.delta-backend.xyz/collections/nightlights-hd-3bands/items
