### ISSUE TITLE
Add GEOGLAM dataset to the API

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/cloud-optimized-data-pipelines#127]
For each dataset, we will follow the following steps:

## Identify the dataset and what the processing needs are
1. Identify dataset and where it will be accessed from. 

These files are available from s3://covid-eo-data/agriculture-cropmonitor/ we can probably publish the files from that location as believe we have done for other collections such as https://staging-stac.delta-backend.xyz/collections/no2-monthly-diff/items

~If the dataset is ongoing (i.e. new files are continuously added and should be included in the dashboard), design and construct the forward-processing workflow.~

~If appropriate, create COG conversion code and verify the COG output with a data product expert (for example, someone at the DAAC which hosts the native format) by sharing in a visual interface.~

## Design the metadata and publish to the Dev API

1. Review conventions for generating STAC collection and item metadata:
   - Collections: https://github.com/NASA-IMPACT/delta-backend/issues/29 and STAC version 1.0 specification for collections
   - Items: https://github.com/NASA-IMPACT/delta-backend/issues/28 and STAC version 1.0 specification for items
   - NOTE: The delta-backend instructions are specific to datasets for the climate dashboard, however not all datasets are going to be a part of the visual layers for the dashboard so I believe you can ignore the instructions that are specific to "dashboard" extension, "item_assets" in the collection and "cog_default" asset type in the item
  
3. After reviewing the STAC documentation for collections and items and reviewing existing scripts for generating collection metadata (generally with SQL) and item metadata, generate or reuse scripts for your collection and a few items to publish to the testing API. There is some documentation and examples for how to generate a pipeline or otherwise document your dataset workflow in https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines. We would like to maintain the scripts folks are using to publish datasets in that repo so we can easily re-run those datasets ingest and publish workflows if necessary.

4.  If necessary, request access and credentials to the dev database and ingest and publish to the Dev API. Submit a PR with the manual or CDK scripts used to run the workflow to publish to the Dev API and include links to the published datasets in the Dev API

## Publish to the Staging API

Once the PR is approved, we can merge and publish those datasets to the Staging API

**Comment by abarciauskas-bgse** [comment]
@alukach @xhagrg @slesaad @tracetechnical I know you all are busy but we need to get this published by May 13 so whomever can pick it up next would be great, should be straight forward.

**Comment by alukach** [comment]
If nobody has any opposition, I'd like to take this on in hopes of becoming better acquainted with the data ingestion process.  I won't be offended if someone else would rather just get it done being that they likely will have a higher velocity given their familiarity with the project.

**Comment by abarciauskas-bgse** [comment]
@alukach thanks so much for raising your hand, I super appreciate it!

@xhagrg and @slesaad are probably most familiar with the pipelines at this point so perhaps they can provide some initial guidance.

In addition to the documentation in the README there is also https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines/blob/main/scripts/insert_collections.md for inserting collections.

**Comment by alukach** [comment]
> s3://covid-eo-data/agriculture-cropmonitor/

@abarciauskas-bgse Which AWS account is this?

**Comment by abarciauskas-bgse** [comment]
@alukach you should have credentials to this account though, my fault for not sending them to you sooner, will do so over slack

**Comment by abarciauskas-bgse** [comment]
Oh interesting - I'm not aware of how to do that or what the SSO means in the case of AWS accounts.

**Comment by alukach** [comment]
@abarciauskas-bgse Where can I find information about the dataset's:

* temporal interval
* license
* title/description
* whether it is periodic or not on the dashboard
* the dashboard time density

**Comment by abarciauskas-bgse** [comment]
temporal interval - monthly - if you look at https://github.com/NASA-IMPACT/covid-api/blob/develop/covid_api/db/static/datasets/agriculture.json#L12 we just want the files that start with `CropMonitor_{date}` and the dates are
license
title/description
whether it is periodic or not on the dashboard
the dashboard time density

**Comment by alukach** [comment]
## Steps Taken

Below are the steps taken to trigger ingestion for the dev environment.

### Create collection:

Checkout https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines/tree/refactor ([@ad1c8f2](https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines/commit/ad1c8f2d7aa53d8d2dca658a2e49c6c5b4c0a524))

Run collection script (assumes you're configured with your correct AWS profile and the AWS region of `us-east-1`):

```sh
➤ APP_NAME=delta-simple-ingest ENV=dev python scripts/collection.py geoglam
Inserting collections:
/Users/alukach/Projects/devseed/veda/cloud-optimized-data-pipelines/scripts/../data/collections/geoglam.json
delta-simple-ingest-dev-lambda-pgstac-loader-fn
{'ResponseMetadata': {'RequestId': 'f92f0048-cb10-4bce-b75b-d198e0690b8d', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Tue, 10 May 2022 20:23:35 GMT', 'content-type': 'application/json', 'content-length': '4', 'connection': 'keep-alive', 'x-amzn-requestid': 'f92f0048-cb10-4bce-b75b-d198e0690b8d', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amzn-trace-id': 'root=1-627ac9c5-533c35b65cdea7044001a35f;sampled=0'}, 'RetryAttempts': 0}, 'StatusCode': 200, 'ExecutedVersion': '$LATEST', 'Payload': <botocore.response.StreamingBody object at 0x10a61fbe0>}
```

### Kickoff step function

**Workflow**: [delta-simple-ingest-dev-stepfunction-discover](https://us-east-1.console.aws.amazon.com/states/home?region=us-east-1#/statemachines/view/arn:aws:states:us-east-1:853558080719:stateMachine:delta-simple-ingest-dev-stepfunction-discover)

**Input**:

```json
{
  "collection": "geoglam",
  "prefix": "agriculture-cropmonitor/",
  "bucket": "covid-eo-data",
  "filename_regex": "^(.*).tif$",
  "discovery": "s3"
}
```

**Comment by alukach** [comment]
Completed nearly identical steps for `stage` environment:

* https://staging-stac.delta-backend.xyz/collections/geoglam
* http://delta-staging-stac-browser.s3-website-us-east-1.amazonaws.com/collections/geoglam
* https://staging-stac.delta-backend.xyz/collections/geoglam/items
* http://delta-staging-stac-browser.s3-website-us-east-1.amazonaws.com/collections/geoglam/items

@abarciauskas-bgse I believe we can close this ticket

**Comment by anayeaye** [comment]
Quick observation about how the data were provided (not how we ingested):
I noticed that there was not an option to adjust the rescaling `/cog/viewer` endpoint so I had a look at the image metadata. These GEOGLAM geotiffs are valid COG but are structurally a little different than some of the other COGs we are working with so I wanted to note it if we bump into anything surprising when using these data (maybe a little slower map loads?). 

**Differences**
- `COMPRESSION`=`LZW` instead of `DEFLATE`
- `LAYOUT`=`COG` is not set in `Image Structure`
- Overviews are not provided.

**Rio Cogeo Comparison**
`rio cogeo info /vsis3/covid-eo-data/agriculture-cropmonitor/CropMonitor_202204.tif`
```
Driver: GTiff
File: /vsis3/covid-eo-data/agriculture-cropmonitor/CropMonitor_202204.tif
COG: True
Compression: LZW
ColorSpace: None

Profile
  Width:      36000
  Height:      18000
  Bands:      1
  Tiled:      True
  Dtype:      uint8
  NoData:      99.0
  Alpha Band:    False
  Internal Mask:  False
  Interleave:    BAND
  ColorMap:     False
  ColorInterp:   (‘gray’,)
  Scales:      (1.0,)
  Offsets:     (0.0,)

Geo
  Crs:       EPSG:4326
  Origin:      (-180.0, 90.0)
  Resolution:    (0.01, -0.01)
  BoundingBox:   (-180.0, -90.0, 180.0, 90.0)
  MinZoom:     0
  MaxZoom:     4

Image Metadata
  AREA_OR_POINT: Area
  DataType: Generic

Image Structure
  COMPRESSION: LZW
  INTERLEAVE: BAND

IFD
  Id   Size      BlockSize   Decimation      
  0    36000x18000  256x256    0

COG Validation info
  - The file is greater than 512xH or 512xW, it is recommended to include internal overviews (warning)
```

`rio cogeo info /vsis3/climatedashboard-data/social_vulnerability_index/svi_2018_tract_housing_wgs84_nopop_cog.tif`
```
Driver: GTiff
File: /vsis3/climatedashboard-data/social_vulnerability_index/svi_2018_tract_housing_wgs84_nopop_cog.tif
COG: True
Compression: DEFLATE
ColorSpace: None

Profile
  Width:      13353
  Height:      6297
  Bands:      1
  Tiled:      True
  Dtype:      float32
  NoData:      -3.3999999521443642e+38
  Alpha Band:    False
  Internal Mask:  False
  Interleave:    BAND
  ColorMap:     False
  ColorInterp:   (‘gray’,)
  Scales:      (1.0,)
  Offsets:     (0.0,)

Geo
  Crs:       EPSG:4326
  Origin:      (-178.23333334, 71.383332688)
  Resolution:    (0.00833333330000749, -0.00833333329998412)
  BoundingBox:   (-178.23333334, 18.908332897999998, -66.958333785, 71.383332688)
  MinZoom:     1
  MaxZoom:     7

Image Metadata
  AREA_OR_POINT: Area
  OVR_RESAMPLING_ALG: NEAREST

Image Structure
  COMPRESSION: DEFLATE
  INTERLEAVE: BAND
  LAYOUT: COG

IFD
  Id   Size      BlockSize   Decimation      
  0    13353x6297   512x512    0
  1    6677x3149   512x512    2
  2    3339x1575   512x512    4
  3    1670x788    512x512    8
  4    835x394    512x512    16
```

**Comment by abarciauskas-bgse** [comment]
Interesting, thanks for sharing this @anayeaye I created a spreadsheet just to see the differences / similarities more easily, sharing here in case it's helpful:
https://docs.google.com/spreadsheets/d/1mbYX8Mmq-CmuIidOCo7VB99xukyAuqRggcD16rhzNjc/edit#gid=0

Seems like the COG-relevant differences, data shape and data type are also distinct but that is more about the nature of the underlying data than the COG structure from what I understand, is the difference in compression (LZW v DEFLATE) and the lack of overviews in the GEOGLAM data. Seems like adding overviews would be important due to the size of the file. Somewhat surprised it is still considered a valid COG without overviews.
