### ISSUE TITLE
Close all open PRs on this repo?

### ISSUE THREAD

**Issue by gadomski** [NASA-IMPACT/cloud-optimized-data-pipelines#361]
Since this repo is being sunsetted (https://github.com/NASA-IMPACT/veda-data-pipelines/pull/360), should we close all open PRs? Or is there work there that should be ported over to **veda-data**? I don't have enough background to know the answer at this time.

For reference, here's the open PRs with a brief summary (I've included checkboxes for when the PRs are closed/ported):

- [x] https://github.com/NASA-IMPACT/veda-data-pipelines/pull/352: Adds two new collections (`eis_fire_fireline.json` and `ls8-surface-temperature-covid-19-changing-landscape.json`) and has quite a bit of lambda and deploy work. Not reviewed
- [x] https://github.com/NASA-IMPACT/veda-data-pipelines/pull/338: A small adjustment to `dashboard:time_density` fields and some of the step functions on four CMIP collections
- [x] https://github.com/NASA-IMPACT/veda-data-pipelines/pull/318: Some href and other fixups for three `eis_fire_*` collections
- [x] https://github.com/NASA-IMPACT/veda-data-pipelines/pull/314: Some collections-specific tweaks to handle vector ingests, I think. Marked WIP but not a draft 🤷🏼 
- [x] https://github.com/NASA-IMPACT/veda-data-pipelines/pull/311: Adds _a ton_ of collections
- [x] https://github.com/NASA-IMPACT/veda-data-pipelines/pull/277: More collections
- [x] https://github.com/NASA-IMPACT/veda-data-pipelines/pull/205: CMIP6 and some infrastructure work

**Comment by jsignell** [comment]
A nuclear option would be to close them all with a note and let people reopen them on veda-data if they are still relevant.

**Comment by gadomski** [comment]
Done, thanks all.
