### ISSUE TITLE
Module which generates STAC metadata for COG in S3 (Starting with SO2)

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/cloud-optimized-data-pipelines#60]
For NO2 and SO2 datasets, Zach will be uploading annual COGs to S3 so we want to write a STAC metadata generation module that takes a collection name and S3 URL and writes STAC metadata to our STAC database.

Acceptance criteria: Given an input of an SO2 COG URL in S3, generate STAC metadata.

This module will not be able to rely on looking up metadata in CMR (double checking this assumption). I believe we want to write a module which knows how to extract the temporal date time either from the file name (e.g. a regex on s3://climatedashboard-data/OMSO2PCA/OMSO2PCA_LUT_SCD_2005.tif which returns 2005) and the spatial extent from the file itself. The SO2 files are global but that information can also be discovered using gdal or rio-cogeo.

Another ticket will cover triggering this STAC metadata function given an S3 directory.

**Comment by jvntf** [comment]
I suggest we adapt the [stac-gen](https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines/tree/ab/add-cdk-pipeline/stac-gen) handler to query CMR only if the granule id is provided, otherwise it can extract the datetime from the filename. Perhaps we also pass a regex param to the handler so it is easy to configure.

Currently the stac item is generated directly from the cog so that section can stay the same. 

Event object passed to handler would be
```
{
   collection: '' required)
   s3_filename: '', (required)
   granule_id: '' (optional)
}
```

**Comment by abarciauskas-bgse** [comment]
Just posting some conversation from slack to keep track:

2 additional things to consider:
* the regex for different collections to parse datetime (or other metadata information) will likely be very different, so parsing information from the filename will almost definitely depend on the collection
* The use case where we're using the files themselves and not CMR records is usually where we're going to be getting a bunch of files uploaded to S3 so it might make sense to have an entirely different workflow

However neither of those items mean you shouldn't re-use the STAC metadata generation code and logic that can query either CMR or the filename for metadata.

Just in the case of using the filename, the regex for date time should also be configurable based on the collection. And we will probably want some way of discovering files in S3 or triggering the workflow based off new collections in S3.

For SO2 and NO2 I imagine all the files will be put in S3 at once so I think it makes sense to include another task to discover all the files in a given S3 location and queue them for STAC metadata generation

@jvntf noted: mod existing stac-gen module to expect either a granule_id or a filename regex in the input, and throw an error if not.

@jvntf I will create a new ticket for `add a new s3 discovery task to list the contents of a s3 location, to be used in a new state machine config`

**Comment by abarciauskas-bgse** [comment]
https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines/issues/67
