### ISSUE TITLE
Test ICESat-2 L4 Monthly Gridded Sea Ice Thickness can be reprojected as a data layer to a dashboard

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/cloud-optimized-data-pipelines#63]
1. [x] Identify dataset and where it will be accessed from. Check it's a good source with science team. Ask about specific variables and required spatial and temporal extent. Note most datasets will require back processing (e.g. generating cloud-optimized data for historical data).
    - Source: https://nsidc.org/data/IS2SITMOGR4/versions/1
    - Variable?
    - Temporal extent is 1 November 2018 to date, ongoing dataset
2. [x] Verify the COG output with the science team by sharing in a visual interface.

**Comment by abarciauskas-bgse** [comment]
I started to look at this a little bit, but the projection doesn't seem to be handled correctly. It is using (according to documentation) EPSG 3411 so I have tried a number of things to get it to re-project to 3857 but no luck so far. It also appears the data is fairly coarse but it's hard to tell.

**Comment by abarciauskas-bgse** [comment]
@slesaad I have been working on trying to get the projection from 3411 to 3857 to work in https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines/blob/5d0d37e25436d901b3a9cdab49e9807bc5bca762/cogify/handler.py but nothing looks quite right.

![Screen Shot 2022-02-07 at 11 29 55 AM](https://user-images.githubusercontent.com/15016780/152865090-8e601210-474b-4cfa-b62c-13107a79b415.png)
![Screen Shot 2022-02-07 at 12 19 19 PM](https://user-images.githubusercontent.com/15016780/152865137-980079a0-6caf-480d-b873-93c23def294a.png)

I was just having trouble figuring out how to get it from it's native projection (which I believe to be EPSG 3411) to the web mercator projection we use for the dashboard. I tried a few things but it either just throws an error or displays in the wrong place, using rio viz.

I think we want to know:
* What does it look like in web mercator if we can figure out we're re-projecting it correctly
* Nice to have: what would it take to use https://docs.mapbox.com/mapbox-gl-js/example/projections/ in the dashboard for this dataset and does it help?

**Comment by slesaad** [comment]
I opened the netcdf file in panoply, and the `ice_thickness` variable looks like this: (hoping this answers the first question)
![image](https://user-images.githubusercontent.com/7830949/153084692-4a75da40-121a-455f-b2f4-a8567cabdb17.png)

still trying to re-project, haven't had much success

**Comment by abarciauskas-bgse** [comment]
Cool, good to see what the data looks like. I don't know much about panoply but it's good to see that it can be reprojected in a way that looks reasonable.

**Comment by slesaad** [comment]
The issue was that the netCDF file when converted to a GeoTiff didn't have the related affine transformation matrix attached. This was solved by calculating the affine transform using the known width/height and bounds of the data. Attaching the transform to the GeoTIFF `profile` when creating the tiff using `rasterio` created a complete GeoTIFF with all the metadata. 

One that was created, @abarciauskas-bgse 's gdal commands were used to re-project the GeoTIFF to the web mercator projection (EPSG:3857).

The resultant GeoTIFF looks like this:
![image](https://user-images.githubusercontent.com/7830949/154714693-a8a99ff0-a28e-4c59-a6c5-31569240d169.png)

**Comment by abarciauskas-bgse** [comment]
Closing this ticket for now
