### ISSUE TITLE
Add Hurricane Ida and Maria nightlights data to staging API

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/cloud-optimized-data-pipelines#74]
- [x]  Identify dataset and where it will be accessed from. Ask about specific variables and required spatial and temporal extent. 

The files have been uploaded to s3://climatedashboard-data/delivery/FinalBMHD_Ida2021/ and s3://climatedashboard-data/delivery/BMHD_Maria_Stages/

They were uploaded to /delivery so that we can use that directory as the staging location before moving them to the same bucket but under their appropriate collection names TBD.

~See additional information about temporal extent below. Spatial extent can be read from the file metadata.~
~We probably need to identify the bands with variables and get some documentation on these datasets but some of that may be acquired from the links below as well.~

- [ ] Write and verify the collection and item metadata output with testing STAC API
- [ ] Deploy in staging API

=====================================================================================
### Hurricane Maria

Ranjay Shrestha from GSFC provided this information in an email about the temporal metadata for Hurricane Maria and links to articles about the :

>Timelines are as follows:
>* Stage 0, baseline Image (Before Hurricane Maria);
>* Stage 1, immediate damage assessment period following Hurricane Maria ( Average night lights Sep. 20 to Nov. 20, 2017);
>* Stage 2, ensuing relief efforts led by FEMA and the US military (Average night lights Nov. 21, 2017 to Jan. 20 2018);
>* Stage 3, recovery efforts led by PREPA and the US Army Corps of Engineers ( Average night lights  Jan. 21 to Mar. 20, 2018)
>
>Here are the links to the [Science Visualization Studio article: NASA's Black Marble night lights used to examine disaster recovery in Puerto Rico](https://svs.gsfc.nasa.gov/4658) and our [PR Paper: Satellite-based assessment of electricity restoration efforts in Puerto Rico after Hurricane Maria](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0218883) for your reference.

Spatial extent can likely be read from the file metadata

### Hurricane Ida

[NASA's Earth Observatory: Satellite Observes Power Outages in New Orleans](https://earthobservatory.nasa.gov/images/148777/satellite-observes-power-outages-in-new-orleans)

The files themselves have the "temporal" metadata as the dates August9 and August31 and the article identifies the year of 2021.

Spatial extent can likely be read from the file metadata

**Comment by abarciauskas-bgse** [comment]
This will be our first environmental justice story dataset from what I understand. For now we should just focus on making sure we have a stac metadata generation pipeline that works for this dataset.

I think we should we also have a ticket to design how the metadata and delta-config should be for a dataset that is targeted at telling a specific story - and actually more generally, **to represent a specific natural event.**

We will presumably need:

- Another ticket to bring in the existing black marble data from the COVID dashboard for just general data exploration in the "Economic" Thematic area. I think the metadata generation for these datasets will be a little bit different given these data for Ida and Maria is for a specific natural event and the other blackmarble data is general purpose for different cities (formerly known as spotlight areas)
- Another ticket to design and implement story telling with the dashboard and delta-config

**Comment by jvntf** [comment]
created stac records for BMHD_Ida 

cc/ @abarciauskas-bgse

**Comment by jvntf** [comment]
Holding off on Hurricane Maria because we should discuss how to treat these dates. They are average over time period, should we just define them as the last date in the range?

**Comment by abarciauskas-bgse** [comment]
@jvntf I think it is compliant with the STAC item spec to have a `start_datetime` and `end_datetime` and set `datetime` to `null`, looking at https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#properties-object - does the pgSTAC database permit this? I'm checking with Ranjay about a datetime for "Stage 0".

**Comment by abarciauskas-bgse** [comment]
Whomever continues to work on these datasets for the dashboard may want to continue the conversation on whether it should be part of the existing black marble collection (https://j2wlly6xg8.execute-api.us-east-1.amazonaws.com/collections/nightlights-hd-monthly) or a new collection like https://j2wlly6xg8.execute-api.us-east-1.amazonaws.com/collections/BMHD_Ida. @anayeaye made a good point that if it's essentially the same product but just different in space and time it should be a part of the current BM collection `nightlights-hd-monthly`.

**Comment by abarciauskas-bgse** [comment]
From Ranjay, the stage 0 COG for Maria should have temporal extent `start_datetime: July 21, 2017` and `end_datetime: September 19, 2017` (properly formatted of course)

>The Stage 0, baseline Image (Before Hurricane Maria), is from average night lights July 21 to Sept 19, 2017.

**Comment by anayeaye** [comment]
I didn't realize that these event-based nightlights captures were also going to be averaged over custom event-based durations so I agree that this is distinct from the existing nightlights-hd-monthly collection. 

If this is expected to be a relatively small number of items that will already need specific start_datetime and end_datetime, maybe we can also add item [descriptions](https://github.com/radiantearth/stac-spec/blob/master/item-spec/common-metadata.md#stac-common-metadata) with the explanatory text about the relative stage the item represents (Stage 0 baseline image before hurricane Maria...).

**Comment by anayeaye** [comment]
@jvntf - was just chatting with @leothomas about this, too. I hadn't thought about the rio-stac implications and I do not know for sure how the stac-fastapi+pgstac handles null datetimes--I will find out and report back. 

My sense is that, for this case, setting a nominal datetime _and_ using start/end datetimes will work best because I would expect users to search this kind of data over a year or broad seasonal range.

The spec does allow datetime=`null` but this [stac-spec discussion](https://github.com/radiantearth/stac-spec/blob/master/best-practices.md#datetime-selection) suggests it might be useful for much longer time ranges like data cubes that could represent 100 years.

**Comment by anayeaye** [comment]
@jvntf I take that back, after stac office hours this week it sounds like we are better off using either start/end or datetime. Pgstac supports  both, so the delta stac and raster APIs are both expected to work seamlessly for items with start/end datetimes.

**Comment by jvntf** [comment]
Thanks @anayeaye 

Inserted maria data into database using `start_datetime` and `end_datetime`, `datetime` set to None

**Comment by xhagrg** [comment]
@abarciauskas-bgse @anayeaye based on NASA-IMPACT/veda-data#58, looks like we are wanting to push the night light data to the existing collection. Is that correct? If so, I can just have the files moved and re-ingest the data.

**Comment by abarciauskas-bgse** [comment]
@xhagrg can we close this issue? I think I see all the expected items in https://staging-stac.delta-backend.xyz/collections/nightlights-hd-monthly/items?limit=200

**Comment by xhagrg** [comment]
sure. Closing now.

**Comment by abarciauskas-bgse** [comment]
@xhagrg just noticed with @freitagb that there is something going on with the dates and hoping you can help me figure out what's up.

The files in the bucket are for August 9 and August 31

<img width="1477" alt="Screen Shot 2022-05-10 at 4 53 45 PM" src="https://user-images.githubusercontent.com/15016780/167720083-7c986a26-88cf-4d02-b5b7-4b75ff85f7e4.png">

but the dates published are for August 31 and September 9

http://delta-staging-stac-browser.s3-website-us-east-1.amazonaws.com/collections/nightlights-hd-3bands

Do you know which is correct?

**Comment by xhagrg** [comment]
august 8 is correct. Got lost on translation. Updating...!

**Comment by xhagrg** [comment]
re-ingested. the files should appear properly now.

**Comment by abarciauskas-bgse** [comment]
Awesome thank you!

**Comment by freitagb** [comment]
Thanks @xhagrg - so as i understand it we have a pre-event image (August 8), a mid-event image (August 31), but no post-event image. Is that correct?

**Comment by xhagrg** [comment]
Yes, no post-event image for Ida. We can ask for the new files. Which dates do you want?
