### ISSUE TITLE
Add blue tarp detection layer

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/cloud-optimized-data-pipelines#79]
Acceptance criteria is that STAC metadata exists for blue tarp detections.

There is a simple STAC viewer http://delta-dev-stac-browser.s3-website-us-east-1.amazonaws.com/ and there should be STAC database information in secure systems manager (can check with @anayeaye or @leothomas or @jvntf about the endpoint and credentials)

We need to work with Kumar and Iksha as they may have created GeoTiffs already

1. - [ ] Identify dataset and where it will be accessed from (probably S3). Identify specific variables and required spatial and temporal extent. 
2. - [x] If the dataset is ongoing - for one event
3. - [ ] Verify the COG output with the science team by sharing in a visual interface.
4. - [x] Design and create the STAC collection metadata
5. - [x] Design and create the STAC item metadata. Verify the metadata output with STAC API developers and any systems which may be depending on this STAC metadata (e.g. the front-end dev team).
6. - [ ] Engage the science team to add any required background information on the methodology used to derive the dataset.

**Comment by leothomas** [comment]
Bluetarp detections are live! 

https://drive.google.com/file/d/15LtnBqVMSAhu31KAW1bbmIbZQQIq29vc/view?usp=sharing

**Comment by slesaad** [comment]
-  [x]  Upload COGs to S3 bucket - [here](https://s3.console.aws.amazon.com/s3/buckets/climatedashboard-data?region=us-east-1&prefix=Hurrican_Ida_Blue_Tarps/&showversions=false)
- [ ] Test STAC collection metadata generation (?)
- [x] Test STAC item metadata generation locally
- [ ] Run the step function for STAC metadata generation/ingest

Currently, the step function is failing at STAC item metadata creation step.

**Comment by abarciauskas-bgse** [comment]
@slesaad I did just write some documentation on how to add collection metadata into this PR: https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines/pull/80/files

Let me know if its helpful and feel welcome to add yourself as a reviewer :)

**Comment by slesaad** [comment]
Thanks @abarciauskas-bgse , it was very easy to follow; I was able to add collection metadata for[ blue tarps ](http://delta-dev-stac-browser.s3-website-us-east-1.amazonaws.com/?t=1)

**Comment by slesaad** [comment]
I added a stac item for blue tarps. It appears in this item link: https://j2wlly6xg8.execute-api.us-east-1.amazonaws.com/collections/Hurrican_Ida_Blue_Tarps/items/70001_detections_2021-09-26.tif
Also is linked to the relevant collection:
```
{
      "rel": "collection",
      "type": "application/json",
      "href": "https://j2wlly6xg8.execute-api.us-east-1.amazonaws.com/collections/Hurrican_Ida_Blue_Tarps"
},
```
however, when I go to the collection/item url: https://j2wlly6xg8.execute-api.us-east-1.amazonaws.com/collections/Hurrican_Ida_Blue_Tarps/items, it’s not listed there

**Comment by slesaad** [comment]
I don't know what the issue was, but after I added all the item metadata; everything seems to be listed.

The collection and item metadata can be viewed in the STAC viewer here: http://delta-dev-stac-browser.s3-website-us-east-1.amazonaws.com/

**Comment by jvntf** [comment]
@slesaad were you able to successfully run the step functions to insert this blue tarp data after adding the collection?

**Comment by slesaad** [comment]
@jvntf unfortunately no. I tried that first, but it threw some errors and i didn't want to mess with the stack in case someone else was using it, so i ingested the items from my local machine

**Comment by abarciauskas-bgse** [comment]
We will need to revisit this workflow, given there will soon be updated files in `s3://climatedashboard-data/delivery/Hurricane_Ida_Blue_Tarps/`  uploaded by @xhagrg

**Comment by abarciauskas-bgse** [comment]
@xhagrg mentioned that looking at s3://climatedashboard-data/Hurricane_Ida_Blue_Tarps/ are we not storing the original scenes for those zipcodes? Just the detections?

**Comment by xhagrg** [comment]
Yeah, currently in that bucket only has one tif file and i am assuming it's just the detection and not the original scenes we used for detection. If we are thinking about the visual aspect of the story, we do need a way to look at the original images along with the detections. I will be uploading the new detections and original files into `s3://climatedashboard-data/delivery/Hurricane_Ida_Blue_Tarps/` today. Hopefully that will make things clearer.

**Comment by xhagrg** [comment]
Yes, that's what i meant. We will have a `{zip-code}_detection.tif` and a `{zip-code}_original.tif` files.

**Comment by abarciauskas-bgse** [comment]
@xhagrg following up on https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines/pull/107 - do we want to have 2 collections for blue tarp data - one for the original files (can you remind me where those images came from?) and one for the detections? This presumably makes it easier to define layers, however in general I don't think visualization use cases should be the only thing driving metadata design.

@anayeaye let me know if you have ideas about metadata design for a dataset like blue tarp data, where the images, as far as I understand, come in pairs: each zipcode has one original file and one blue tarp detections file.

**Comment by anayeaye** [comment]
@xhagrg @abarciauskas-bgse - Maybe we can have a quick sync about blue tarp data? I collected some thoughts below but I'm a little unclear on the data. In particular how do we need to render these on a map? Side by side? An overlay?

Potential problems/additional work if we use a single collection:
- The ingest method we've been using only generates raster and proj extension properties for a single asset
- The UI config will need custom presets for displaying detection data (if we use cog_default the UI can render the map data the same way it does for other collections)

Assumptions for a single collection:
- Every item in collection will always have one original and one detection asset each with a unique COG url
- Every asset is a single band geotiff. As in: we don't need to apply a custom band combination to display the base/original tiff on a map, if a multi band combination is needed for a false color image of either asset I think that merits separate collections. 
- Every asset has exactly the same projection and spatial/temporal extent. If the detection tiffs are a different size from the original they'd need to be stored in separate items and at that point two collections could make more sense.

Using two collections:
- For discoverability, I prefer a single collection of items with multiple assets.
- For consistency, there has been a preference for flat single-asset collections in delta metadata design so far: [delta-backend issue 32](https://github.com/NASA-IMPACT/delta-backend/issues/32) 
- If we did generate separate collections for original and detection, existing tooling will work with no additional effort.

**Comment by xhagrg** [comment]
@anayeaye @abarciauskas-bgse should we have different collections for different hurricanes or just one general "blue-tarp-detection" collection that contains all the events? It would be good to have it in one collection.

**Comment by abarciauskas-bgse** [comment]
I believe we discussed this Monday and decided to have just one general "blue-tarp-detection" collection right @xhagrg ?

**Comment by abarciauskas-bgse** [comment]
@xhagrg is this complete?

**Comment by xhagrg** [comment]
re-ingesting some files today. it will be then done.

**Comment by xhagrg** [comment]
This has been re-ingested and ready for review. 
https://staging-stac.delta-backend.xyz/collections/blue-tarp-detection/items
https://staging-stac.delta-backend.xyz/collections/blue-tarp-planetscope/items
