### ISSUE TITLE
Ingest HLS subsets into the staging API

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/cloud-optimized-data-pipelines#95]
In DEV API ingest and publish `HLSS30.002` and `HLSL30.002` for the temporal and spatial extends of Hurricanes Ida and Maria
- [x] Check HLSS30.002 collection metadata looks ok in DEV API
- [x] Add HLSL30 via SQL script similar too https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines/blob/main/scripts/collections-sql/HLSS30.002.sql 
- [x] Ingest items into each collection using https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines/blob/main/dataset-workflows/hls-cdk/cdk/cdk_stack.py. This stack queries CMR and then kicks off a workflow for doing bulk inserts using ndjson.
- [x] Check with Aimee and Alexandra the updated collection and item STAC json looks good
- [ ] Open PR for changes

In new staging API
- [x] Follow same steps for creating the STAC collection metadata
- [x] Run the STAC metadata generation for items via triggering the HLS lambda `cog-pipeline-hls-builtinfunctionidHLSS30002discove`
- [ ] Verify with Alexandra

**Comment by abarciauskas-bgse** [comment]
Need to solve this first https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines/issues/89

**Comment by abarciauskas-bgse** [comment]
We're going to ingest and publish the data as the metadata is currently defined. @anayeaye @sharkinsspatial my understanding is we may still need to implement a custom function via a change like https://github.com/NASA-IMPACT/eoAPI/commit/8457367ae1e75c506aa16fd54172edddaa161fcb so if you agree, I'll add another task to do that and close #89

**Comment by anayeaye** [comment]
@abarciauskas-bgse quick HLS in Pgstac v0.5 note: we are going to need to configure partitioning for this dataset before ingesting any items into the collection (but everything else we are doing so far will work with no additional configuration). 

I have a task to document/share that info for ingest with links to the relevant pgstac v0.5 documents and I will also link the info here.

**Comment by abarciauskas-bgse** [comment]
awesome thanks @anayeaye, do you think we should table this ingest task because we will need to re-ingest it for proper partitioning or could we do the repartitioning once version 0.5 of the database is in use?

**Comment by anayeaye** [comment]
Yeah, that sounds right

**Comment by slesaad** [comment]
Collection metadata:

[HLSS30.002](https://dev-stac.delta-backend.xyz/collections/HLSS30.002)
[HLSL30.002](https://dev-stac.delta-backend.xyz/collections/HLSL30.002)

**Comment by slesaad** [comment]
I've added items for Ida/Maria spatial and temporal extents to both the collections.
They're linked:
https://dev-stac.delta-backend.xyz/collections/HLSS30.002/items
https://dev-stac.delta-backend.xyz/collections/HLSL30.002/items

Please validate that the collection (previous comment) and item metadata looks right. @anayeaye @abarciauskas-bgse

**Comment by abarciauskas-bgse** [comment]
🙌🏽 awesome, metadata looks reasonable so far. Would be interested if we could get 👀 from @sharkinsspatial or @freitagb since they are most familiar with these collections. Did you have to write any new code to do this data ingest and is that in a branch somewhere?

**Comment by freitagb** [comment]
@slesaad - i think this looks date range and bounding box looks good for the most part. New Orleans bounding box may need to be expanded a bit, but it's certainly a good starting point and shouldn't be a blocker.

**Comment by slesaad** [comment]
The stac metadata has been published to the staging api.
Find them here: https://staging-stac.delta-backend.xyz/collections/HLSS30.002 , https://staging-stac.delta-backend.xyz/collections/HLSL30.002
@anayeaye please verify
