### ISSUE TITLE
Add NO2 monthly and NO2 monthly diff to staging API

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/cloud-optimized-data-pipelines#98]
Dataset already exists in testing API 

https://j2wlly6xg8.execute-api.us-east-1.amazonaws.com/collections/no2-monthly-diff
https://j2wlly6xg8.execute-api.us-east-1.amazonaws.com/collections/no2-monthly 

I believe @anayeaye did this from her local machine

@anayeaye of course it makes most sense if you work on this but if you have time to add your scripts to this repo (in a new directory in `dataset-workflows/`) that would be 💯

**Comment by abarciauskas-bgse** [comment]
Legacy ticket: https://github.com/NASA-IMPACT/delta-backend/issues/24

**Comment by anayeaye** [comment]
I added the python used to load these datasets locally to the `dataset-workflows` in PR #101
